version: 2
jobs:
  build:
    
    working_directory: ~/pelican-bookstore

    docker:
      - image: circleci/openjdk@sha256:314c68fdea1aad957dfe32e2d5d813a443128cf9036dc1b9ef8d73e6f472613c
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
    

      - checkout

      - restore_cache:
          key: pelican-bookstore-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: pelican-bookstore-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/pelican-bookstore-0.0.1-SNAPSHOT.jar
          
         
         
         
         
         
         
  
